# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Authentication(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authentication_id': 'str',
        'authtype': 'str'
    }

    attribute_map = {
        'authentication_id': 'authentication_id',
        'authtype': 'authtype'
    }

    def __init__(self, authentication_id=None, authtype=None):  # noqa: E501
        """Authentication - a model defined in Swagger"""  # noqa: E501

        self._authentication_id = None
        self._authtype = None
        self.discriminator = None

        if authentication_id is not None:
            self.authentication_id = authentication_id
        if authtype is not None:
            self.authtype = authtype

    @property
    def authentication_id(self):
        """Gets the authentication_id of this Authentication.  # noqa: E501

        Unique authentication type record locator. It is absent when not persisted.  # noqa: E501

        :return: The authentication_id of this Authentication.  # noqa: E501
        :rtype: str
        """
        return self._authentication_id

    @authentication_id.setter
    def authentication_id(self, authentication_id):
        """Sets the authentication_id of this Authentication.

        Unique authentication type record locator. It is absent when not persisted.  # noqa: E501

        :param authentication_id: The authentication_id of this Authentication.  # noqa: E501
        :type: str
        """

        self._authentication_id = authentication_id

    @property
    def authtype(self):
        """Gets the authtype of this Authentication.  # noqa: E501

        Type of authentication.  # noqa: E501

        :return: The authtype of this Authentication.  # noqa: E501
        :rtype: str
        """
        return self._authtype

    @authtype.setter
    def authtype(self, authtype):
        """Sets the authtype of this Authentication.

        Type of authentication.  # noqa: E501

        :param authtype: The authtype of this Authentication.  # noqa: E501
        :type: str
        """
        allowed_values = ["BASIC", "FORM", "AUTO", "CERT"]  # noqa: E501
        if authtype not in allowed_values:
            raise ValueError(
                "Invalid value for `authtype` ({0}), must be one of {1}"  # noqa: E501
                .format(authtype, allowed_values)
            )

        self._authtype = authtype

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Authentication, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Authentication):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
