# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AuthenticationScriptFailureData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'failure_type': 'str',
        'script_type': 'str',
        'script_failure': 'ScriptFailureData'
    }

    attribute_map = {
        'failure_type': 'failure_type',
        'script_type': 'script_type',
        'script_failure': 'script_failure'
    }

    def __init__(self, failure_type=None, script_type=None, script_failure=None):  # noqa: E501
        """AuthenticationScriptFailureData - a model defined in Swagger"""  # noqa: E501

        self._failure_type = None
        self._script_type = None
        self._script_failure = None
        self.discriminator = None

        if failure_type is not None:
            self.failure_type = failure_type
        if script_type is not None:
            self.script_type = script_type
        if script_failure is not None:
            self.script_failure = script_failure

    @property
    def failure_type(self):
        """Gets the failure_type of this AuthenticationScriptFailureData.  # noqa: E501

        Depends on the type of script. Currently this value will return a constant - SELENIUM_SCRIPT_FAILURE_DATA.  # noqa: E501

        :return: The failure_type of this AuthenticationScriptFailureData.  # noqa: E501
        :rtype: str
        """
        return self._failure_type

    @failure_type.setter
    def failure_type(self, failure_type):
        """Sets the failure_type of this AuthenticationScriptFailureData.

        Depends on the type of script. Currently this value will return a constant - SELENIUM_SCRIPT_FAILURE_DATA.  # noqa: E501

        :param failure_type: The failure_type of this AuthenticationScriptFailureData.  # noqa: E501
        :type: str
        """

        self._failure_type = failure_type

    @property
    def script_type(self):
        """Gets the script_type of this AuthenticationScriptFailureData.  # noqa: E501

        The type of script. Currently this value will return a constant - SELENIUM.  # noqa: E501

        :return: The script_type of this AuthenticationScriptFailureData.  # noqa: E501
        :rtype: str
        """
        return self._script_type

    @script_type.setter
    def script_type(self, script_type):
        """Sets the script_type of this AuthenticationScriptFailureData.

        The type of script. Currently this value will return a constant - SELENIUM.  # noqa: E501

        :param script_type: The script_type of this AuthenticationScriptFailureData.  # noqa: E501
        :type: str
        """

        self._script_type = script_type

    @property
    def script_failure(self):
        """Gets the script_failure of this AuthenticationScriptFailureData.  # noqa: E501

        Details of the script failure.  # noqa: E501

        :return: The script_failure of this AuthenticationScriptFailureData.  # noqa: E501
        :rtype: ScriptFailureData
        """
        return self._script_failure

    @script_failure.setter
    def script_failure(self, script_failure):
        """Sets the script_failure of this AuthenticationScriptFailureData.

        Details of the script failure.  # noqa: E501

        :param script_failure: The script_failure of this AuthenticationScriptFailureData.  # noqa: E501
        :type: ScriptFailureData
        """

        self._script_failure = script_failure

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthenticationScriptFailureData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthenticationScriptFailureData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
