# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CrawlConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'disabled': 'bool',
        'scripts': 'list[CrawlScript]'
    }

    attribute_map = {
        'disabled': 'disabled',
        'scripts': 'scripts'
    }

    def __init__(self, disabled=None, scripts=None):  # noqa: E501
        """CrawlConfiguration - a model defined in Swagger"""  # noqa: E501

        self._disabled = None
        self._scripts = None
        self.discriminator = None

        if disabled is not None:
            self.disabled = disabled
        if scripts is not None:
            self.scripts = scripts

    @property
    def disabled(self):
        """Gets the disabled of this CrawlConfiguration.  # noqa: E501

        If true, the automated crawler is disabled.  # noqa: E501

        :return: The disabled of this CrawlConfiguration.  # noqa: E501
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """Sets the disabled of this CrawlConfiguration.

        If true, the automated crawler is disabled.  # noqa: E501

        :param disabled: The disabled of this CrawlConfiguration.  # noqa: E501
        :type: bool
        """

        self._disabled = disabled

    @property
    def scripts(self):
        """Gets the scripts of this CrawlConfiguration.  # noqa: E501

        List of optional, valid script identifiers.  # noqa: E501

        :return: The scripts of this CrawlConfiguration.  # noqa: E501
        :rtype: list[CrawlScript]
        """
        return self._scripts

    @scripts.setter
    def scripts(self, scripts):
        """Sets the scripts of this CrawlConfiguration.

        List of optional, valid script identifiers.  # noqa: E501

        :param scripts: The scripts of this CrawlConfiguration.  # noqa: E501
        :type: list[CrawlScript]
        """

        self._scripts = scripts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CrawlConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CrawlConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
