# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EmbeddedPlatformApplication(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'platform_applications': 'list[PlatformApplication]'
    }

    attribute_map = {
        'platform_applications': 'platform_applications'
    }

    def __init__(self, platform_applications=None):  # noqa: E501
        """EmbeddedPlatformApplication - a model defined in Swagger"""  # noqa: E501

        self._platform_applications = None
        self.discriminator = None

        if platform_applications is not None:
            self.platform_applications = platform_applications

    @property
    def platform_applications(self):
        """Gets the platform_applications of this EmbeddedPlatformApplication.  # noqa: E501


        :return: The platform_applications of this EmbeddedPlatformApplication.  # noqa: E501
        :rtype: list[PlatformApplication]
        """
        return self._platform_applications

    @platform_applications.setter
    def platform_applications(self, platform_applications):
        """Sets the platform_applications of this EmbeddedPlatformApplication.


        :param platform_applications: The platform_applications of this EmbeddedPlatformApplication.  # noqa: E501
        :type: list[PlatformApplication]
        """

        self._platform_applications = platform_applications

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmbeddedPlatformApplication, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmbeddedPlatformApplication):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
