# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EmbeddedDetailedScanOccurrence(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scan_occurrences': 'list[DetailedScanOccurrence]'
    }

    attribute_map = {
        'scan_occurrences': 'scan_occurrences'
    }

    def __init__(self, scan_occurrences=None):  # noqa: E501
        """EmbeddedDetailedScanOccurrence - a model defined in Swagger"""  # noqa: E501

        self._scan_occurrences = None
        self.discriminator = None

        if scan_occurrences is not None:
            self.scan_occurrences = scan_occurrences

    @property
    def scan_occurrences(self):
        """Gets the scan_occurrences of this EmbeddedDetailedScanOccurrence.  # noqa: E501


        :return: The scan_occurrences of this EmbeddedDetailedScanOccurrence.  # noqa: E501
        :rtype: list[DetailedScanOccurrence]
        """
        return self._scan_occurrences

    @scan_occurrences.setter
    def scan_occurrences(self, scan_occurrences):
        """Sets the scan_occurrences of this EmbeddedDetailedScanOccurrence.


        :param scan_occurrences: The scan_occurrences of this EmbeddedDetailedScanOccurrence.  # noqa: E501
        :type: list[DetailedScanOccurrence]
        """

        self._scan_occurrences = scan_occurrences

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmbeddedDetailedScanOccurrence, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmbeddedDetailedScanOccurrence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
