# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PlatformApplication(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'linked_scan_target_url': 'str',
        'name': 'str',
        'uuid': 'str'
    }

    attribute_map = {
        'id': 'id',
        'linked_scan_target_url': 'linked_scan_target_url',
        'name': 'name',
        'uuid': 'uuid'
    }

    def __init__(self, id=None, linked_scan_target_url=None, name=None, uuid=None):  # noqa: E501
        """PlatformApplication - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._linked_scan_target_url = None
        self._name = None
        self._uuid = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if linked_scan_target_url is not None:
            self.linked_scan_target_url = linked_scan_target_url
        if name is not None:
            self.name = name
        if uuid is not None:
            self.uuid = uuid

    @property
    def id(self):
        """Gets the id of this PlatformApplication.  # noqa: E501

        Identifier of the Veracode Platform application.  # noqa: E501

        :return: The id of this PlatformApplication.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PlatformApplication.

        Identifier of the Veracode Platform application.  # noqa: E501

        :param id: The id of this PlatformApplication.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def linked_scan_target_url(self):
        """Gets the linked_scan_target_url of this PlatformApplication.  # noqa: E501

        Target URL of the scan linked to the Veracode Platform application. If not present, this application is not linked to a URL scan.  # noqa: E501

        :return: The linked_scan_target_url of this PlatformApplication.  # noqa: E501
        :rtype: str
        """
        return self._linked_scan_target_url

    @linked_scan_target_url.setter
    def linked_scan_target_url(self, linked_scan_target_url):
        """Sets the linked_scan_target_url of this PlatformApplication.

        Target URL of the scan linked to the Veracode Platform application. If not present, this application is not linked to a URL scan.  # noqa: E501

        :param linked_scan_target_url: The linked_scan_target_url of this PlatformApplication.  # noqa: E501
        :type: str
        """

        self._linked_scan_target_url = linked_scan_target_url

    @property
    def name(self):
        """Gets the name of this PlatformApplication.  # noqa: E501

        Veracode Platform application name.  # noqa: E501

        :return: The name of this PlatformApplication.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PlatformApplication.

        Veracode Platform application name.  # noqa: E501

        :param name: The name of this PlatformApplication.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def uuid(self):
        """Gets the uuid of this PlatformApplication.  # noqa: E501

        Veracode Platform application UUID.  # noqa: E501

        :return: The uuid of this PlatformApplication.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this PlatformApplication.

        Veracode Platform application UUID.  # noqa: E501

        :param uuid: The uuid of this PlatformApplication.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlatformApplication, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlatformApplication):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
