# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SeleniumCommandInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'target': 'str',
        'value': 'str',
        'targets': 'list[TargetListData]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'target': 'target',
        'value': 'value',
        'targets': 'targets'
    }

    def __init__(self, id=None, name=None, target=None, value=None, targets=None):  # noqa: E501
        """SeleniumCommandInfo - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._target = None
        self._value = None
        self._targets = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if target is not None:
            self.target = target
        if value is not None:
            self.value = value
        if targets is not None:
            self.targets = targets

    @property
    def id(self):
        """Gets the id of this SeleniumCommandInfo.  # noqa: E501

        Identifier of the command.  # noqa: E501

        :return: The id of this SeleniumCommandInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SeleniumCommandInfo.

        Identifier of the command.  # noqa: E501

        :param id: The id of this SeleniumCommandInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SeleniumCommandInfo.  # noqa: E501

        Name of the command.  # noqa: E501

        :return: The name of this SeleniumCommandInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SeleniumCommandInfo.

        Name of the command.  # noqa: E501

        :param name: The name of this SeleniumCommandInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def target(self):
        """Gets the target of this SeleniumCommandInfo.  # noqa: E501

        The target HTML element of the command.  # noqa: E501

        :return: The target of this SeleniumCommandInfo.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this SeleniumCommandInfo.

        The target HTML element of the command.  # noqa: E501

        :param target: The target of this SeleniumCommandInfo.  # noqa: E501
        :type: str
        """

        self._target = target

    @property
    def value(self):
        """Gets the value of this SeleniumCommandInfo.  # noqa: E501

        The value to set for the target. Nullable.  # noqa: E501

        :return: The value of this SeleniumCommandInfo.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this SeleniumCommandInfo.

        The value to set for the target. Nullable.  # noqa: E501

        :param value: The value of this SeleniumCommandInfo.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def targets(self):
        """Gets the targets of this SeleniumCommandInfo.  # noqa: E501

        Additional targets for the HTML element.  # noqa: E501

        :return: The targets of this SeleniumCommandInfo.  # noqa: E501
        :rtype: list[TargetListData]
        """
        return self._targets

    @targets.setter
    def targets(self, targets):
        """Sets the targets of this SeleniumCommandInfo.

        Additional targets for the HTML element.  # noqa: E501

        :param targets: The targets of this SeleniumCommandInfo.  # noqa: E501
        :type: list[TargetListData]
        """

        self._targets = targets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SeleniumCommandInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SeleniumCommandInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
