# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.crawl_configuration import CrawlConfiguration  # noqa: E501
from swagger_client.rest import ApiException


class TestCrawlConfiguration(unittest.TestCase):
    """CrawlConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCrawlConfiguration(self):
        """Test CrawlConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.crawl_configuration.CrawlConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
