# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.connection_attempt_data import ConnectionAttemptData  # noqa: E501
from swagger_client.rest import ApiException


class TestConnectionAttemptData(unittest.TestCase):
    """ConnectionAttemptData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionAttemptData(self):
        """Test ConnectionAttemptData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.connection_attempt_data.ConnectionAttemptData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
