# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.v_1_analysis_api_api import V1AnalysisApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestV1AnalysisApiApi(unittest.TestCase):
    """V1AnalysisApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.v_1_analysis_api_api.V1AnalysisApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_scans_to_analysis_using_post(self):
        """Test case for add_scans_to_analysis_using_post

        Adds one or more new URLs to the Dynamic Analysis. You can also add URLs by updating the analysis.  # noqa: E501
        """
        pass

    def test_create_analysis_using_post(self):
        """Test case for create_analysis_using_post

        Creates a new Dynamic Analysis for the account, if the user has access to the account. Returns the URL of the  new analysis in the HTTP response header.   # noqa: E501
        """
        pass

    def test_delete_analysis_using_delete(self):
        """Test case for delete_analysis_using_delete

        Deletes the Dynamic Analysis for the provided identifier. You can only hard-delete an analysis if it has never run.  # noqa: E501
        """
        pass

    def test_delete_scan_using_delete(self):
        """Test case for delete_scan_using_delete

        Deletes the URL scan with the specified dentifier. You can only delete scans that have never run.  # noqa: E501
        """
        pass

    def test_find_all_scans_for_analysis_using_get(self):
        """Test case for find_all_scans_for_analysis_using_get

        Returns a list of all occurrences of the Dynamic Analysis.  # noqa: E501
        """
        pass

    def test_find_analysis_audits_by_id_using_get(self):
        """Test case for find_analysis_audits_by_id_using_get

        Returns a list of audit logs for the specified Dynamic Analysis.  # noqa: E501
        """
        pass

    def test_find_analysis_by_id_using_get(self):
        """Test case for find_analysis_by_id_using_get

        Returns the Dynamic Analysis for the provided identifier.  # noqa: E501
        """
        pass

    def test_find_analysis_summaries_using_get(self):
        """Test case for find_analysis_summaries_using_get

        Returns a list of Dynamic Analyses for the current organization or a specified, alternate organization.  # noqa: E501
        """
        pass

    def test_find_platform_applications_using_get(self):
        """Test case for find_platform_applications_using_get

        Returns a list of applications in the Veracode Platform.  # noqa: E501
        """
        pass

    def test_find_scan_audits_by_id_using_get(self):
        """Test case for find_scan_audits_by_id_using_get

        Returns a list of audits (activity logs) for the provided URL scan identifier.  # noqa: E501
        """
        pass

    def test_find_scan_by_id_using_get(self):
        """Test case for find_scan_by_id_using_get

        Returns a URL scan.  # noqa: E501
        """
        pass

    def test_get_scan_configuration_using_get(self):
        """Test case for get_scan_configuration_using_get

        Returns the configuration for the specified URL scan.  # noqa: E501
        """
        pass

    def test_update_analysis_using_put(self):
        """Test case for update_analysis_using_put

        Updates a Dynamic Analysis for the provided identifier.  # noqa: E501
        """
        pass

    def test_update_scan_configuration_using_put(self):
        """Test case for update_scan_configuration_using_put

        Updates the configuration for the specified URL scan.  # noqa: E501
        """
        pass

    def test_update_scan_using_put(self):
        """Test case for update_scan_using_put

        Updates the URL scan request.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
