# coding: utf-8

"""
    Veracode Web Application Scanning Configuration Service API

    Web Application Scanning Configuration API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: veracode@veracode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.v_1_configuration_api_api import V1ConfigurationApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestV1ConfigurationApiApi(unittest.TestCase):
    """V1ConfigurationApiApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.v_1_configuration_api_api.V1ConfigurationApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_code_group_by_id_using_get(self):
        """Test case for find_code_group_by_id_using_get

        Returns the details of a code group.  # noqa: E501
        """
        pass

    def test_get_account_scan_capacity_summary_using_get(self):
        """Test case for get_account_scan_capacity_summary_using_get

        Returns the scan capacity summary for the organization.  # noqa: E501
        """
        pass

    def test_get_code_groups_using_get(self):
        """Test case for get_code_groups_using_get

        Returns a list of code groups  # noqa: E501
        """
        pass

    def test_get_default_configuration_using_get(self):
        """Test case for get_default_configuration_using_get

        Returns the default Dynamic Analysis configuration for the organization.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
